-- +goose Up
CREATE    SCHEMA IF NOT EXISTS auth;

CREATE    SCHEMA IF NOT EXISTS ai;

CREATE    SCHEMA IF NOT EXISTS payment;

-- +goose Down
DROP      SCHEMA IF EXISTS auth CASCADE;

DROP      SCHEMA IF EXISTS ai CASCADE;

DROP      SCHEMA IF EXISTS payment CASCADE;