// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AiConversation struct {
	ID        int32              `json:"id"`
	Uuid      pgtype.UUID        `json:"uuid"`
	Name      string             `json:"name"`
	UserID    int32              `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AiMessage struct {
	ID             int32              `json:"id"`
	Content        string             `json:"content"`
	Role           string             `json:"role"`
	ConversationID int32              `json:"conversation_id"`
	Tokens         pgtype.Int4        `json:"tokens"`
	FinishReason   pgtype.Text        `json:"finish_reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AuthUser struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Phone     string             `json:"phone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PaymentOperation struct {
	ID              int32            `json:"id"`
	Destination     string           `json:"destination"`
	OperationNumber string           `json:"operation_number"`
	OperationDate   pgtype.Timestamp `json:"operation_date"`
	SenderName      pgtype.Text      `json:"sender_name"`
	AmountSent      pgtype.Numeric   `json:"amount_sent"`
	Currency        string           `json:"currency"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	AdditionalNotes pgtype.Text      `json:"additional_notes"`
}
